name: envoy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  
  cupertino_icons:
  flutter:
    sdk: flutter
  
  # Assets
  flutter_localizations:
    sdk: flutter
  go_router:
  intl:

  # Widgets
  modal_bottom_sheet:
  sliding_up_panel:
  auto_size_text:
  equatable:
  sheet:

  # Location and Geocoding
  location:
  maplibre_gl:
      git:
        url: https://github.com/m0nac0/flutter-maplibre-gl.git
        ref: main
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:
  flutter_lints:
  build_runner:

flutter_gen:
  output: lib/screen/widget/custom/

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/files/

  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded/SF-Pro-Rounded-Black.otf
        - asset: assets/fonts/SF-Pro-Rounded/SF-Pro-Rounded-Bold.otf
        - asset: assets/fonts/SF-Pro-Rounded/SF-Pro-Rounded-Heavy.otf
        - asset: assets/fonts/SF-Pro-Rounded/SF-Pro-Rounded-Light.otf
        - asset: assets/fonts/SF-Pro-Rounded/SF-Pro-Rounded-Medium.otf
        - asset: assets/fonts/SF-Pro-Rounded/SF-Pro-Rounded-Regular.otf
        - asset: assets/fonts/SF-Pro-Rounded/SF-Pro-Rounded-SemiBold.otf
        - asset: assets/fonts/SF-Pro-Rounded/SF-Pro-Rounded-Thin.otf
        - asset: assets/fonts/SF-Pro-Rounded/SF-Pro-Rounded-UltraLight.otf
